/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ventura
 */
public class CalculadoraFrame extends javax.swing.JFrame {

    public String contenidoPantalla;
    /**
     * Creates new form CalculadoraFrame
     */
    public CalculadoraFrame() {
        initComponents();
        contenidoPantalla="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaTexto = new javax.swing.JTextField();
        operacionesPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        numerosPanel = new javax.swing.JPanel();
        unoBoton = new javax.swing.JButton();
        dosBoton = new javax.swing.JButton();
        tresBoton = new javax.swing.JButton();
        cuatroBoton = new javax.swing.JButton();
        cincoBoton = new javax.swing.JButton();
        seisBoton = new javax.swing.JButton();
        sieteBoton = new javax.swing.JButton();
        ochoBoton = new javax.swing.JButton();
        nueveBoton = new javax.swing.JButton();
        puntoBoton = new javax.swing.JButton();
        ceroBoton = new javax.swing.JButton();
        masmenosBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        pantallaTexto.setEditable(false);
        pantallaTexto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantallaTexto.setPreferredSize(new java.awt.Dimension(200, 60));
        getContentPane().add(pantallaTexto, java.awt.BorderLayout.NORTH);

        operacionesPanel.setPreferredSize(new java.awt.Dimension(100, 200));
        operacionesPanel.setLayout(new java.awt.GridLayout(4, 2));

        jButton1.setText("C");
        operacionesPanel.add(jButton1);

        jButton2.setText("<--");
        operacionesPanel.add(jButton2);

        jButton3.setText("+");
        operacionesPanel.add(jButton3);

        jButton4.setText("-");
        operacionesPanel.add(jButton4);

        jButton5.setText("x");
        operacionesPanel.add(jButton5);

        jButton6.setText("/");
        operacionesPanel.add(jButton6);

        jButton7.setText("( )");
        operacionesPanel.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setText("=");
        operacionesPanel.add(jButton8);

        getContentPane().add(operacionesPanel, java.awt.BorderLayout.EAST);

        numerosPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        numerosPanel.setLayout(new java.awt.GridLayout(4, 3));

        unoBoton.setText("1");
        unoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoBotonActionPerformed(evt);
            }
        });
        numerosPanel.add(unoBoton);

        dosBoton.setText("2");
        dosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosBotonActionPerformed(evt);
            }
        });
        numerosPanel.add(dosBoton);

        tresBoton.setText("3");
        numerosPanel.add(tresBoton);

        cuatroBoton.setText("4");
        numerosPanel.add(cuatroBoton);

        cincoBoton.setText("5");
        numerosPanel.add(cincoBoton);

        seisBoton.setText("6");
        numerosPanel.add(seisBoton);

        sieteBoton.setText("7");
        numerosPanel.add(sieteBoton);

        ochoBoton.setText("8");
        numerosPanel.add(ochoBoton);

        nueveBoton.setText("9");
        numerosPanel.add(nueveBoton);

        puntoBoton.setText(".");
        numerosPanel.add(puntoBoton);

        ceroBoton.setText("0");
        numerosPanel.add(ceroBoton);

        masmenosBoton.setText("+/-");
        numerosPanel.add(masmenosBoton);

        getContentPane().add(numerosPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoBotonActionPerformed
        contenidoPantalla = contenidoPantalla + "1";
        pantallaTexto.setText(contenidoPantalla);
        
    }//GEN-LAST:event_unoBotonActionPerformed

    private void dosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosBotonActionPerformed
        contenidoPantalla = contenidoPantalla + "2";
        pantallaTexto.setText(contenidoPantalla);
    }//GEN-LAST:event_dosBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ceroBoton;
    private javax.swing.JButton cincoBoton;
    private javax.swing.JButton cuatroBoton;
    private javax.swing.JButton dosBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton masmenosBoton;
    private javax.swing.JButton nueveBoton;
    private javax.swing.JPanel numerosPanel;
    private javax.swing.JButton ochoBoton;
    private javax.swing.JPanel operacionesPanel;
    private javax.swing.JTextField pantallaTexto;
    private javax.swing.JButton puntoBoton;
    private javax.swing.JButton seisBoton;
    private javax.swing.JButton sieteBoton;
    private javax.swing.JButton tresBoton;
    private javax.swing.JButton unoBoton;
    // End of variables declaration//GEN-END:variables
}
