/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ventura
 */
public class CalculadoraFrame7A extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraFrame7A
     */
    public CalculadoraFrame7A() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaTextField = new javax.swing.JTextField();
        numerosPanel = new javax.swing.JPanel();
        unoBoton = new javax.swing.JButton();
        dosBoton = new javax.swing.JButton();
        tresBoton = new javax.swing.JButton();
        cuatroBoton = new javax.swing.JButton();
        cincoBoton = new javax.swing.JButton();
        seisBoton = new javax.swing.JButton();
        sieteBoton = new javax.swing.JButton();
        ochoBoton = new javax.swing.JButton();
        nueveBoton = new javax.swing.JButton();
        puntoBoton = new javax.swing.JButton();
        ceroBoton = new javax.swing.JButton();
        masMenosBoton = new javax.swing.JButton();
        operacionesPanel = new javax.swing.JPanel();
        borrarBoton = new javax.swing.JButton();
        borrarCaracterBoton = new javax.swing.JButton();
        masBoton = new javax.swing.JButton();
        menosBoton = new javax.swing.JButton();
        multiplicacionBoton = new javax.swing.JButton();
        divisionBoton = new javax.swing.JButton();
        parentesisBoton = new javax.swing.JButton();
        igualBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        pantallaTextField.setEditable(false);
        pantallaTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(pantallaTextField, java.awt.BorderLayout.NORTH);

        numerosPanel.setLayout(new java.awt.GridLayout(4, 3));

        unoBoton.setText("1");
        numerosPanel.add(unoBoton);

        dosBoton.setText("2");
        numerosPanel.add(dosBoton);

        tresBoton.setText("3");
        numerosPanel.add(tresBoton);

        cuatroBoton.setText("4");
        numerosPanel.add(cuatroBoton);

        cincoBoton.setText("5");
        numerosPanel.add(cincoBoton);

        seisBoton.setText("6");
        numerosPanel.add(seisBoton);

        sieteBoton.setText("7");
        numerosPanel.add(sieteBoton);

        ochoBoton.setText("8");
        numerosPanel.add(ochoBoton);

        nueveBoton.setText("9");
        numerosPanel.add(nueveBoton);

        puntoBoton.setText(".");
        numerosPanel.add(puntoBoton);

        ceroBoton.setText("0");
        numerosPanel.add(ceroBoton);

        masMenosBoton.setText("+/-");
        numerosPanel.add(masMenosBoton);

        getContentPane().add(numerosPanel, java.awt.BorderLayout.CENTER);

        operacionesPanel.setLayout(new java.awt.GridLayout(4, 2));

        borrarBoton.setText("C");
        operacionesPanel.add(borrarBoton);

        borrarCaracterBoton.setText("<--");
        operacionesPanel.add(borrarCaracterBoton);

        masBoton.setText("+");
        operacionesPanel.add(masBoton);

        menosBoton.setText("-");
        operacionesPanel.add(menosBoton);

        multiplicacionBoton.setText("x");
        operacionesPanel.add(multiplicacionBoton);

        divisionBoton.setText("/");
        operacionesPanel.add(divisionBoton);

        parentesisBoton.setText("( )");
        operacionesPanel.add(parentesisBoton);

        igualBoton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        igualBoton.setText("=");
        operacionesPanel.add(igualBoton);

        getContentPane().add(operacionesPanel, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame7A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame7A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame7A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame7A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraFrame7A().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBoton;
    private javax.swing.JButton borrarCaracterBoton;
    private javax.swing.JButton ceroBoton;
    private javax.swing.JButton cincoBoton;
    private javax.swing.JButton cuatroBoton;
    private javax.swing.JButton divisionBoton;
    private javax.swing.JButton dosBoton;
    private javax.swing.JButton igualBoton;
    private javax.swing.JButton masBoton;
    private javax.swing.JButton masMenosBoton;
    private javax.swing.JButton menosBoton;
    private javax.swing.JButton multiplicacionBoton;
    private javax.swing.JButton nueveBoton;
    private javax.swing.JPanel numerosPanel;
    private javax.swing.JButton ochoBoton;
    private javax.swing.JPanel operacionesPanel;
    private javax.swing.JTextField pantallaTextField;
    private javax.swing.JButton parentesisBoton;
    private javax.swing.JButton puntoBoton;
    private javax.swing.JButton seisBoton;
    private javax.swing.JButton sieteBoton;
    private javax.swing.JButton tresBoton;
    private javax.swing.JButton unoBoton;
    // End of variables declaration//GEN-END:variables
}
